### ISSUE TITLE
Does it work on image  segmentation?

### ISSUE THREAD

**Issue by sunshuofeng** [alldbi/SuperMix#2]
If supermix is used for image segmentation, should we replace KL with an IOU that evaluates x_hat with k inputs and then maximize it？

**Comment by alldbi** [comment]
Hi, 
Yes, it can be used to improve segmentation performance. However, SuperMix should not be changed. You can use a trained classifier and generate mixed images, and then use the mixing masks to produce the corresponding dense segmentation maps. Afterward, the generated images and segments can be used to train the segmentation model.

**Comment by sunshuofeng** [comment]
Thanks  for your answer! SuperMix is very amazing!
