### ISSUE TITLE
Why tolerance  percent is so high

### ISSUE THREAD

**Issue by sunshuofeng** [alldbi/SuperMix#3]
When I was looking at the code, I suddenly noticed that you set the tol parameter to 70 percent by default, which means that if the batch is 8, only 2-3 supermix images will be returned. Is it because the performance of supermix is very good, so it does not need a lot of data？ in order to speed up the training, we set high tol parameters.

**Comment by alldbi** [comment]
Hi,
I set the tol to 70% for a specific experiment on ImageNet. The default value on CIFAR is 10% and on ImageNet is 50%. It just speeds up the mixing process. I will change this value to its default one in the next commit. Thank you.

**Comment by sunshuofeng** [comment]
Ok! Thanks for your answer
