### ISSUE TITLE
Question of Table 1. experiment

### ISSUE THREAD

**Issue by caisarl76** [alldbi/SuperMix#5]
Hi, @alldbi thank you for your interesting work

I'm trying to reproduce the results of table 1. on your paper, but I can't find the training code for it. 
Or is it just using the train_teacher.py code with loading the produced SuperMix dataset? (+ by using get_cifar100_dataloaders_sample and class CIFAR100InstanceSample?)

**Comment by alldbi** [comment]
Hi, 
I am glad that our work is interesting to you. For training the model, train_student.py should be used. Before that, sueprmix.py should be run to generate the mixed that. 

Please let me know if you have further questions. 

Thanks, 
Ali
